build-job:
  stage: build
  script:
    - maven compile

test-job:
  stage: test
  script:
    - maven test

deploy-prod:
  stage: deploy
  script:
    - maven package
    - dpl --provider=heroku --app=ef420-simplewebapp --api-key=14eb8559-b004-4ebd-9059-f7e09305b68a
